import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";

import { EXAMPLE_BLUEPRINT } from "@/features/blueprints/example";
import { generateApplicationFiles } from "@/features/generation/codegen";
import {
  kebabCase,
  pascalCase,
  routeSegments,
  snakeCase,
} from "@/features/generation/codegen/identifiers";
import { generateSchemaSql } from "@/features/generation/codegen/sql";

describe("identifiers", () => {
  it("converts names to code-safe identifiers", () => {
    expect(pascalCase("book a visit!")).toBe("BookAVisit");
    expect(snakeCase("Owner email")).toBe("owner_email");
    expect(kebabCase("My Appointments")).toBe("my-appointments");
  });

  it("converts routes to safe segments", () => {
    expect(routeSegments("/book")).toEqual(["book"]);
    expect(routeSegments("/admin/reports")).toEqual(["admin", "reports"]);
    expect(routeSegments("/")).toEqual([]);
  });
});

describe("generateSchemaSql", () => {
  it("creates a table per data model with typed columns", () => {
    const sql = generateSchemaSql(EXAMPLE_BLUEPRINT);
    expect(sql).toContain("create table public.appointment");
    expect(sql).toContain("owner_email text not null");
    expect(sql).toContain("date_and_time timestamptz not null");
    expect(sql).toContain("enable row level security");
  });
});

describe("generateApplicationFiles", () => {
  const files = generateApplicationFiles(EXAMPLE_BLUEPRINT);
  const paths = files.map((file) => file.path);
  const byPath = new Map(files.map((file) => [file.path, file.content]));

  it("produces a complete runnable project", () => {
    for (const required of [
      "package.json",
      "tsconfig.json",
      "app/layout.tsx",
      "app/page.tsx",
      "app/globals.css",
      "components/blocks.tsx",
      "lib/types.ts",
      "lib/sample-data.ts",
      "supabase/schema.sql",
      "README.md",
      ".env.example",
    ]) {
      expect(paths).toContain(required);
    }
  });

  it("creates one page per blueprint route", () => {
    expect(paths).toContain("app/book/page.tsx");
    expect(paths).toContain("app/schedule/page.tsx");
    expect(paths).toContain("app/reports/page.tsx");
  });

  it("gives form pages fields from the matched data model", () => {
    const bookPage = byPath.get("app/book/page.tsx")!;
    expect(bookPage).toContain("DataForm");
    expect(bookPage).toContain("Pet name");
  });

  it("declares types from data models", () => {
    const types = byPath.get("lib/types.ts")!;
    expect(types).toContain("export interface Appointment");
    expect(types).toContain('"owner_email": string');
    expect(types).toContain("export const ROLES");
  });

  it("is honest in the generated README", () => {
    const readme = byPath.get("README.md")!;
    expect(readme).toContain("sample data");
    expect(readme.toLowerCase()).toContain("generated by");
  });

  // Not a real test: writes the generated app to disk for build verification
  // when GEN_OUT is set (used by CI-style local checks).
  it("optionally writes the app to GEN_OUT", () => {
    const out = process.env.GEN_OUT;
    if (!out) return;
    for (const file of files) {
      const full = join(out, file.path);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, file.content);
    }
    expect(true).toBe(true);
  });
});
