import type { ProjectBlueprint } from "@/features/blueprints/schema";
import {
  pascalCase,
  routeSegments,
  snakeCase,
} from "@/features/generation/codegen/identifiers";
import {
  classifyComponent,
  inputTypeForField,
  matchDataModel,
  sampleValueForField,
} from "@/features/generation/prototype";

function tsType(fieldType: string): string {
  const type = fieldType.toLowerCase();
  if (type.includes("bool")) return "boolean";
  if (
    type.includes("number") ||
    type.includes("int") ||
    type.includes("decimal")
  ) {
    return "number";
  }
  return "string";
}

/** Normalized page route: "/" for home-like routes, "/segments" otherwise. */
export function normalizedRoute(route: string): string {
  const segments = routeSegments(route);
  return segments.length === 0 ? "/" : `/${segments.join("/")}`;
}

export function layoutTsx(blueprint: ProjectBlueprint): string {
  const links = blueprint.pages
    .map(
      (page) =>
        `          <Link href=${JSON.stringify(normalizedRoute(page.route))}>${page.name}</Link>`,
    )
    .join("\n");

  return `import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(blueprint.projectName)},
  description: ${JSON.stringify(blueprint.oneSentenceSummary)},
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="site-nav">
          <div className="site-nav-inner">
            <Link href="/" className="brand">
              ${blueprint.projectName}
            </Link>
${links}
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
`;
}

export function homePageTsx(blueprint: ProjectBlueprint): string {
  const cards = blueprint.pages
    .map(
      (page) => `        <div className="card">
          <h2>
            <Link href=${JSON.stringify(normalizedRoute(page.route))}>${page.name}</Link>
          </h2>
          <p className="muted">${page.purpose}</p>
        </div>`,
    )
    .join("\n");

  return `import Link from "next/link";

export default function HomePage() {
  return (
    <div>
      <h1>${blueprint.projectName}</h1>
      <p className="muted">${blueprint.oneSentenceSummary}</p>
      <div>
${cards}
      </div>
      <footer>
        Starter generated by Forge. Sample data only — see README for the
        next steps.
      </footer>
    </div>
  );
}
`;
}

export function typesTs(blueprint: ProjectBlueprint): string {
  const interfaces = blueprint.dataModels.map((model) => {
    const fields = model.fields
      .map((field) => {
        const optional = field.required ? "" : "?";
        const comment = field.description ? ` // ${field.description}` : "";
        return `  ${JSON.stringify(snakeCase(field.name))}${optional}: ${tsType(field.type)};${comment}`;
      })
      .join("\n");
    return `/** ${model.description} */
export interface ${pascalCase(model.name)} {
  id: string;
${fields}
}`;
  });

  const roles = blueprint.roles.map((role) => JSON.stringify(role.name));

  return `// Types generated by Forge from the project blueprint.

${interfaces.join("\n\n")}

export const ROLES = [${roles.join(", ")}] as const;
export type Role = (typeof ROLES)[number];
`;
}

export function sampleDataTs(blueprint: ProjectBlueprint): string {
  const datasets = blueprint.dataModels.map((model) => {
    const rows = [1, 2, 3].map((n) => {
      const fields = model.fields
        .map(
          (field) =>
            `    ${JSON.stringify(snakeCase(field.name))}: ${
              tsType(field.type) === "boolean"
                ? n % 2 === 0
                  ? "false"
                  : "true"
                : tsType(field.type) === "number"
                  ? String(n * 7)
                  : JSON.stringify(`${sampleValueForField(field)}`)
            },`,
        )
        .join("\n");
      return `  {\n    id: ${JSON.stringify(`sample-${n}`)},\n${fields}\n  },`;
    });
    return `export const sample${pascalCase(model.name)}List: ${pascalCase(model.name)}[] = [
${rows.join("\n")}
];`;
  });

  const imports = blueprint.dataModels
    .map((model) => pascalCase(model.name))
    .join(", ");

  return `// Sample data generated by Forge. Replace with real queries when you
// connect your database (schema in supabase/schema.sql).
import type { ${imports} } from "./types";

${datasets.join("\n\n")}
`;
}

export function blocksTsx(): string {
  return `"use client";

// Generic UI blocks used by the generated pages. Sample data only.
import { useState, type FormEvent } from "react";

export interface FormFieldSpec {
  label: string;
  inputType: string;
  required: boolean;
  placeholder: string;
}

export function DataForm({
  title,
  fields,
}: {
  title: string;
  fields: FormFieldSpec[];
}) {
  const [submitted, setSubmitted] = useState(false);

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    // TODO: persist this record once a database is connected.
    setSubmitted(true);
  }

  return (
    <form className="card" onSubmit={handleSubmit}>
      <h3>{title}</h3>
      {fields.map((field) => (
        <div className="field" key={field.label}>
          <label htmlFor={field.label}>
            {field.label}
            {field.required ? " *" : ""}
          </label>
          {field.inputType === "select" ? (
            <select id={field.label} defaultValue="">
              <option value="" disabled>
                Choose…
              </option>
              <option>Option A</option>
              <option>Option B</option>
            </select>
          ) : field.inputType === "checkbox" ? (
            <input id={field.label} type="checkbox" />
          ) : (
            <input
              id={field.label}
              type={field.inputType}
              placeholder={field.placeholder}
            />
          )}
        </div>
      ))}
      <button type="submit" className="primary">
        Submit
      </button>
      {submitted ? (
        <p className="notice" role="status">
          Not saved yet: this starter uses sample data. Connect a database to
          persist records (see README).
        </p>
      ) : null}
    </form>
  );
}

export function DataTable({
  title,
  columns,
  rows,
}: {
  title: string;
  columns: string[];
  rows: string[][];
}) {
  return (
    <div className="card">
      <h3>{title}</h3>
      <table>
        <thead>
          <tr>
            {columns.map((column) => (
              <th key={column}>{column}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={index}>
              {row.map((cell, cellIndex) => (
                <td key={cellIndex}>{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      <p className="muted">Sample rows — replace with real data.</p>
    </div>
  );
}

export function StatCards({
  title,
  items,
}: {
  title: string;
  items: Array<{ label: string; value: string }>;
}) {
  return (
    <div className="card">
      <h3>{title}</h3>
      <div className="stat-grid">
        {items.map((item) => (
          <div className="stat" key={item.label}>
            <div className="muted">{item.label}</div>
            <div className="value">{item.value}</div>
          </div>
        ))}
      </div>
      <p className="muted">Sample values.</p>
    </div>
  );
}

export function ActionButtons({
  title,
  labels,
}: {
  title: string;
  labels: string[];
}) {
  const [message, setMessage] = useState<string | null>(null);
  return (
    <div className="card">
      <h3>{title}</h3>
      <div>
        {labels.map((label) => (
          <button
            key={label}
            type="button"
            className="primary"
            style={{ marginRight: "0.6rem" }}
            onClick={() => setMessage(label)}
          >
            {label}
          </button>
        ))}
      </div>
      {message ? (
        <p className="notice" role="status">
          “{message}” is not wired up yet — add its behavior when you connect
          real data.
        </p>
      ) : null}
    </div>
  );
}
`;
}

/** Generates one page file for a blueprint page. */
export function pageTsx(
  blueprint: ProjectBlueprint,
  page: ProjectBlueprint["pages"][number],
): string {
  const model = matchDataModel(blueprint, page);
  const componentNames = page.components.length
    ? page.components
    : ["Page content"];

  const usedBlocks = new Set<string>();
  const blocks = componentNames.map((component) => {
    const kind = classifyComponent(component);
    if (kind === "form") {
      usedBlocks.add("DataForm");
      const fields = (model?.fields ?? []).slice(0, 6).map((field) => ({
        label: field.name,
        inputType: inputTypeForField(field),
        required: field.required,
        placeholder: sampleValueForField(field),
      }));
      return `      <DataForm title=${JSON.stringify(component)} fields={${JSON.stringify(fields)}} />`;
    }
    if (kind === "table" || kind === "calendar") {
      usedBlocks.add("DataTable");
      const fields = (model?.fields ?? []).slice(0, 4);
      const columns = fields.map((field) => field.name);
      const rows = [0, 1, 2].map(() =>
        fields.map((field) => sampleValueForField(field)),
      );
      return `      <DataTable title=${JSON.stringify(component)} columns={${JSON.stringify(columns)}} rows={${JSON.stringify(rows)}} />`;
    }
    if (kind === "stats") {
      usedBlocks.add("StatCards");
      const label = model ? model.name.toLowerCase() : "records";
      const items = [
        { label: `Total ${label}`, value: "128" },
        { label: "This week", value: "17" },
        { label: "Needs attention", value: "3" },
      ];
      return `      <StatCards title=${JSON.stringify(component)} items={${JSON.stringify(items)}} />`;
    }
    usedBlocks.add("ActionButtons");
    return `      <ActionButtons title=${JSON.stringify(component)} labels={${JSON.stringify(["Primary action", "Secondary"])}} />`;
  });

  const imports =
    usedBlocks.size > 0
      ? `import { ${[...usedBlocks].sort().join(", ")} } from "@/components/blocks";\n\n`
      : "";
  const rolesNote =
    page.allowedRoles.length > 0
      ? `      <p className="muted">Visible to: ${page.allowedRoles.join(", ")} (authentication not wired yet)</p>\n`
      : "";

  return `${imports}export const metadata = { title: ${JSON.stringify(page.name)} };

export default function ${pascalCase(page.name)}Page() {
  return (
    <div>
      <h1>${page.name}</h1>
      <p className="muted">${page.purpose}</p>
${rolesNote}${blocks.join("\n")}
    </div>
  );
}
`;
}
