import type { ProjectBlueprint } from "@/features/blueprints/schema";
import { kebabCase } from "@/features/generation/codegen/identifiers";

export function packageJson(blueprint: ProjectBlueprint): string {
  return `${JSON.stringify(
    {
      name: kebabCase(blueprint.projectName),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^16.2.12",
        react: "^19.2.4",
        "react-dom": "^19.2.4",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
      },
    },
    null,
    2,
  )}\n`;
}

export function tsconfigJson(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"],
    },
    null,
    2,
  )}\n`;
}

export function nextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

export function gitignore(): string {
  return `node_modules
.next
out
.env*
!.env.example
*.tsbuildinfo
next-env.d.ts
`;
}

export function envExample(blueprint: ProjectBlueprint): string {
  const integrationLines = blueprint.integrations
    .map(
      (integration) =>
        `# ${integration.name} — ${integration.purpose}${integration.required ? " (required)" : " (optional)"}\n# ${kebabCase(integration.name).toUpperCase().replace(/-/g, "_")}_API_KEY=`,
    )
    .join("\n\n");

  return `# Environment variables for ${blueprint.projectName}
# Copy to .env.local and fill in values. Never commit real secrets.

# Database (when you connect Supabase; schema in supabase/schema.sql)
# NEXT_PUBLIC_SUPABASE_URL=
# NEXT_PUBLIC_SUPABASE_ANON_KEY=

${integrationLines || "# No integrations planned yet."}
`;
}

export function readme(blueprint: ProjectBlueprint): string {
  const pageList = blueprint.pages
    .map((page) => `- **${page.name}** (\`${page.route}\`) — ${page.purpose}`)
    .join("\n");

  return `# ${blueprint.projectName}

${blueprint.oneSentenceSummary}

This is a starter application generated by [Forge](https://forge.app) from
your approved project blueprint. It runs immediately with sample data so you
can feel the flow; connecting a real database is the documented next step.

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000.

## What's inside

${pageList}

## Honest status

- Pages, navigation, forms, and tables come from your blueprint. ✅
- Data shown is **sample data** defined in \`lib/sample-data.ts\`. Forms do
  not persist yet — each submit handler contains a clearly marked TODO. ⚠️
- \`supabase/schema.sql\` contains the database schema for your data models,
  ready to apply when you connect Supabase. 🔜
- Roles are listed in \`lib/types.ts\`; authentication is not wired yet. 🔜

## Next steps

1. Create a Supabase project and run \`supabase/schema.sql\` in its SQL editor.
2. Add your keys to \`.env.local\` (see \`.env.example\`).
3. Replace the sample-data module with real queries.
`;
}

export function globalsCss(): string {
  return `:root {
  --background: #faf9f7;
  --surface: #ffffff;
  --border: #e4e1dc;
  --text: #23201c;
  --text-muted: #6f6a62;
  --accent: #c2410c;
  --accent-soft: #fbe9dd;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family:
    ui-sans-serif,
    system-ui,
    -apple-system,
    sans-serif;
  background: var(--background);
  color: var(--text);
  line-height: 1.6;
}

a {
  color: inherit;
}

main {
  max-width: 960px;
  margin: 0 auto;
  padding: 2.5rem 1.25rem 4rem;
}

.site-nav {
  border-bottom: 1px solid var(--border);
  background: var(--surface);
}

.site-nav-inner {
  max-width: 960px;
  margin: 0 auto;
  padding: 0.9rem 1.25rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem 1.1rem;
  align-items: center;
}

.site-nav a {
  text-decoration: none;
  color: var(--text-muted);
  font-size: 0.95rem;
}

.site-nav a:hover {
  color: var(--text);
}

.site-nav .brand {
  font-weight: 700;
  color: var(--text);
  margin-right: 0.6rem;
}

.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 1.25rem;
  margin-top: 1.25rem;
}

.muted {
  color: var(--text-muted);
}

.field {
  margin-top: 0.9rem;
}

.field label {
  display: block;
  font-weight: 600;
  font-size: 0.9rem;
}

.field input,
.field select,
.field textarea {
  width: 100%;
  margin-top: 0.3rem;
  padding: 0.55rem 0.7rem;
  border: 1px solid var(--border);
  border-radius: 8px;
  font: inherit;
  background: var(--surface);
}

button.primary {
  margin-top: 1.1rem;
  padding: 0.6rem 1.2rem;
  border: none;
  border-radius: 8px;
  background: var(--accent);
  color: white;
  font: inherit;
  font-weight: 600;
  cursor: pointer;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 0.5rem;
  font-size: 0.95rem;
}

th,
td {
  text-align: left;
  padding: 0.55rem 0.6rem;
  border-bottom: 1px solid var(--border);
}

th {
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--text-muted);
}

.stat-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 0.9rem;
  margin-top: 0.5rem;
}

.stat {
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 0.9rem;
}

.stat .value {
  font-size: 1.6rem;
  font-weight: 700;
}

.notice {
  background: var(--accent-soft);
  border-radius: 8px;
  padding: 0.7rem 0.9rem;
  font-size: 0.9rem;
  margin-top: 0.9rem;
}

footer {
  border-top: 1px solid var(--border);
  margin-top: 3rem;
  padding-top: 1rem;
  font-size: 0.85rem;
  color: var(--text-muted);
}
`;
}
