import type { ProjectBlueprint } from "@/features/blueprints/schema";
import { snakeCase } from "@/features/generation/codegen/identifiers";

function sqlType(fieldType: string): string {
  const type = fieldType.toLowerCase();
  if (type.includes("bool")) return "boolean";
  if (type.includes("date") && type.includes("time")) return "timestamptz";
  if (type.includes("date")) return "date";
  if (type.includes("time")) return "time";
  if (
    type.includes("number") ||
    type.includes("decimal") ||
    type.includes("currency")
  ) {
    return "numeric";
  }
  if (type.includes("int")) return "integer";
  if (type.includes("reference") || type.includes("relation")) return "uuid";
  return "text";
}

/** Generates a PostgreSQL schema from the blueprint's data models. */
export function generateSchemaSql(blueprint: ProjectBlueprint): string {
  const header = `-- Database schema for ${blueprint.projectName}
-- Generated by Forge from the approved blueprint.
-- Apply in the Supabase SQL editor (or psql) when you connect a database.
-- Row-level security is enabled on every table; add policies that match
-- your roles before going to production.
`;

  const tables = blueprint.dataModels.map((model) => {
    const table = snakeCase(model.name);
    const columns = model.fields.map((field) => {
      const column = snakeCase(field.name);
      const notNull = field.required ? " not null" : "";
      const comment = field.description ? ` -- ${field.description}` : "";
      return `  ${column} ${sqlType(field.type)}${notNull},${comment}`;
    });

    const relationshipNotes =
      model.relationships.length > 0
        ? `\n-- Relationships: ${model.relationships.join("; ")}`
        : "";

    return `-- ${model.description}${relationshipNotes}
create table public.${table} (
  id uuid primary key default gen_random_uuid(),
${columns.join("\n")}
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.${table} enable row level security;`;
  });

  return `${header}\n${tables.join("\n\n")}\n`;
}
